#
# Development version
#
version: "3"
services:
  s3:
    tty: true
    # See command here:
    #   https://hub.docker.com/r/minio/minio/
    image: "minio/minio"
    command: "server /data --console-address \":9001\""
    volumes:
      - "minio-data:/data"
    ports:
      - "9000:9000" # service
      - "9001:9001" # web console
    # Variables from stderr:
    #  (also, work as credentials for s3)
    environment:
      MINIO_ROOT_USER: "s3admin"
      MINIO_ROOT_PASSWORD: "s3password"
    networks:
      - s3

  api:
    image: "autochecks-api"
    volumes:
      # Put config into container
      - "./files/api/config:/usr/src/app/config"
    networks:
      - s3
      - autochecks
      - queue

  redis:
    image: "redis:alpine"
    restart: "always"
    ports:
      - "6379:6379"
    networks:
      - queue

  # mongodb:
  #   image: "mongo"

  # bucket-creator:
  #   tty: true
  #   image: "bucket-creator"
  #   build: "./images/bucket-creator"
  #   depends_on:
  #     - s3
  #   networks:
  #     - s3

networks:
  s3: {}
  autochecks: {}
  queue: {}

volumes:
  minio-data: {}
