- name: Cleanup polygon
  hosts: localhost
  tasks:
    - name: "Load common vars"
      include_vars:
        file: "./common_vars.yml"

    - name: "Remove polygon directory"
      file:
        path: "{{ polygon_path }}"
        state: absent
