- name: Prepare build
  hosts: localhost
  vars:
    project_root: "{{ lookup('ansible.builtin.env', 'PWD') }}"
    polygon_path: "{{ project_root }}/polygon"
    repository_dest: "{{ polygon_path }}/package"
    repository_slug: "{{ lookup('ansible.builtin.env', 'REPO_SLUG') }}"
    repository_url: "git@github.com:htmlacademy/{{ repository_slug }}.git"
  tasks:
    - name: "Create polygon for building image"
      file:
        path: "{{ polygon_path }}"
        state: directory
        mode: "0755"

    - name: "Clone repository"
      git:
        repo: "{{ repository_url }}"
        dest: "{{ repository_dest }}"

    - name: "Install dependencies"
      npm:
        path: "{{ repository_dest }}"
        state: present

