- name: Prepare build
  hosts: localhost
  tasks:
    - name: "Load common vars"
      include_vars:
        file: "./common_vars.yml"

    - name: "Create polygon for building image"
      file:
        path: "{{ polygon_path }}"
        state: directory
        mode: "0755"

    - name: "Clone repository"
      git:
        repo: "{{ repository_url }}"
        dest: "{{ repository_dest }}"

    - name: "Install dependencies"
      npm:
        path: "{{ repository_dest }}"
        state: present

